### PR TITLE
Docs build

### LINKED ISSUE #24: Docs not building after renaming.
`Import membrane_curvature` (Line 16) seems to be the problem. 
Docs build otherwise. 

Any suggestion @lilyminium on how to solve this issue?

### PR DESCRIPTION
**Pull request by ojeda-e**
Fixes #24

### CODE REVIEW

**Comment by ojeda-e** [comment]
I will merge this PR since it is a very simple change @lilyminium @IAlibay

**Comment by IAlibay** [comment]
It's not immediately clear to me as to why the import is failing. I think I might be missing something?

**Comment by ojeda-e** [comment]
Thanks for your answer @IAlibay.
It's is not clear to me either. I can't understand why the change here included fixes the issue. 
Even worse considering the test in the CI passes. 

Maybe we can leave this issue open?

**Comment by IAlibay** [comment]
I think I'll defer to @lilyminium here, but if it works in CI but not locally (am I correct in understanding this is the issue you encountered?) I would suspect a conflict in your local environment. I assume you can import that module locally? (outside this test)

**Comment by ojeda-e** [comment]
> I think I'll defer to @lilyminium here, but if it works in CI but not locally (am I correct in understanding this is the issue you encountered?) 

Yes, correct.
And I think you are right @IAlibay and the problem is in my virtual env. Let's wait for @lilyminium's opinion on this.
Thanks ☺️

**Pull request closed without merging**
